dist: xenial
services:
- postgresql
branches:
  only:
  - master
  - develop
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- pip install codacy-coverage
script:
- npm -g install phantomjs
- cd decide
- cp travis_local_settings.py local_settings.py
- python ./manage.py makemigrations
- python ./manage.py migrate
- python ./manage.py loaddata decideDB.json
- python ./manage.py runserver
- python ./manage.py test --keepdb
