dist: xenial
services:
- postgresql
branches:
  only:
  - master
  - develop
addons:
  postgresql: '9.4'
before_script:
- psql -U postgres -c "create user decide password 'decide'"
- psql -U postgres -c "create database test_decide owner decide"
- psql -U postgres -c "ALTER USER decide CREATEDB"
- cp local_settings.example.py local_settings.py
- python manage.py makemigrations
- python manage.py migrate
- python manage.py loaddata decideDB.json
language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
script:
- travis_wait 20 python manage.py test
